services:

  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: entorno_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - entorno_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - entorno_network

  node-app:
    image: node:20
    container_name: node_container
    working_dir: /app
    volumes:
      - ./node-app:/app
    command: sh -c "npm install express pg && node server.js"
    ports:
      - "3000:3000"
    networks:
      - entorno_network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx:/usr/share/nginx/html
    networks:
      - entorno_network

  jupyter:
    image: jupyter/base-notebook
    container_name: jupyter_lab
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter:/home/jovyan/work
    networks:
      - entorno_network

volumes:
  postgres_data:

networks:
  entorno_network:

